bentoml/comfy-pack

nodes/api.py
=> feat: collect comfyui hash, models, custom nodes into snapshot.json

nodes/api.py, nodes/service.py, nodes/setup_workspace.py
=> feat: setup workspace at build time

nodes/api.py
=> fix: missing git urls when freezing requirements

nodes/api.py
=> fix: service py location

nodes/api.py, src/comfy_pack/package.py, src/comfy_pack/setup_workspace.py
=> fix: make setup script self-contained

nodes/api.py, uv.lock
=> fix: build bento api error

nodes/api.py
=> fix: skip seen and excluded packages

src/comfy_pack/cli.py, src/comfy_pack/run.py, src/comfy_pack/service.py
=> fix: specify the workspace for run

src/comfy_pack/service.py
=> fix: remove on shutdown hook

src/comfy_pack/setup_workspace.py
=> fix: don't import bentoml at setup

pyproject.toml, requirements.txt
=> fix: pin bentoml version

src/comfy_pack/service.py
=> fix: remove trailing whitespace

src/comfy_pack/service.py
=> fix: serve from UI has no workspace

src/comfy_pack/cli.py, src/comfy_pack/package.py
=> feat: unpack-bento command

src/comfy_pack/cli.py
=> feat: install reqs.txt from src directory

src/comfy_pack/cli.py
=> feat: pull bento from cloud if not exists

nodes/nodes.py
=> feat(nodes): new node: Save Audio

nodes/nodes.py
=> fix: output audio node

nodes/nodes.py, src/comfy_pack/utils.py, uv.lock
=> feat: support save video node

nodes/nodes.py, src/comfy_pack/utils.py
=> feat: make zip from multiple output if enabled

nodes/nodes.py
=> feat: save text to file node

src/comfy_pack/cli.py, src/comfy_pack/package.py
=> fix: incorrect script path of cm-cli.py
